# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_control_pb2 as device__control__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlCenterStub(object):
    """============================================
    设备控制服务定义
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/device_control.ControlCenter/Register',
                request_serializer=device__control__pb2.RegisterRequest.SerializeToString,
                response_deserializer=device__control__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/device_control.ControlCenter/Heartbeat',
                request_serializer=device__control__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=device__control__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.PullCommands = channel.unary_stream(
                '/device_control.ControlCenter/PullCommands',
                request_serializer=device__control__pb2.PullCommandsRequest.SerializeToString,
                response_deserializer=device__control__pb2.Command.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/device_control.ControlCenter/ReportResult',
                request_serializer=device__control__pb2.CommandResult.SerializeToString,
                response_deserializer=device__control__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.stream_unary(
                '/device_control.ControlCenter/StreamLogs',
                request_serializer=device__control__pb2.LogChunk.SerializeToString,
                response_deserializer=device__control__pb2.StreamLogsResponse.FromString,
                _registered_method=True)


class ControlCenterServicer(object):
    """============================================
    设备控制服务定义
    ============================================

    """

    def Register(self, request, context):
        """设备注册
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """心跳保活
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullCommands(self, request, context):
        """拉取待执行的命令（长连接，流式返回）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """上报命令执行结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request_iterator, context):
        """流式上传日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlCenterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=device__control__pb2.RegisterRequest.FromString,
                    response_serializer=device__control__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=device__control__pb2.HeartbeatRequest.FromString,
                    response_serializer=device__control__pb2.HeartbeatResponse.SerializeToString,
            ),
            'PullCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.PullCommands,
                    request_deserializer=device__control__pb2.PullCommandsRequest.FromString,
                    response_serializer=device__control__pb2.Command.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=device__control__pb2.CommandResult.FromString,
                    response_serializer=device__control__pb2.ReportResponse.SerializeToString,
            ),
            'StreamLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=device__control__pb2.LogChunk.FromString,
                    response_serializer=device__control__pb2.StreamLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device_control.ControlCenter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device_control.ControlCenter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlCenter(object):
    """============================================
    设备控制服务定义
    ============================================

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_control.ControlCenter/Register',
            device__control__pb2.RegisterRequest.SerializeToString,
            device__control__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_control.ControlCenter/Heartbeat',
            device__control__pb2.HeartbeatRequest.SerializeToString,
            device__control__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/device_control.ControlCenter/PullCommands',
            device__control__pb2.PullCommandsRequest.SerializeToString,
            device__control__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device_control.ControlCenter/ReportResult',
            device__control__pb2.CommandResult.SerializeToString,
            device__control__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/device_control.ControlCenter/StreamLogs',
            device__control__pb2.LogChunk.SerializeToString,
            device__control__pb2.StreamLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
